FROM postgres:15
LABEL maintainer="fragarie"
LABEL description="PostreSQL container with added gettext package for using envsubst in SQL initialization"

RUN apt-get update \
  && apt-get install -y --no-install-recommends gettext \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

CMD ["postgres"]
