# Environment variables must be declared in .env file
version: '3'
x-bot-common:
  &bot-common
  environment:
    &bot-common-env
    POSTGRES_DB: tgbot
    POSTGRES_USER: ${PSQL_MASTER_USER}
    POSTGRES_PASSWORD: ${PSQL_MASTER_PASSWORD}
    PGDATA: /var/lib/postgresql/data
  volumes:
    - ./sql:/docker-entrypoint-initdb.d

services:
  pginit:
    <<: *bot-common
    build: botpostgres
    entrypoint: /bin/bash
    command:
      - -c
      - |
        export PSQL_HANDLER_USER=${PSQL_HANDLER_USER} PSQL_HANDLER_PASSWORD=${PSQL_HANDLER_PASSWORD}
        export PSQL_USER=${PSQL_USER} PSQL_PASSWORD=${PSQL_PASSWORD}
        envsubst < /docker-entrypoint-initdb.d/init.sqltemplate > /docker-entrypoint-initdb.d/init.sql
        unset PSQL_HANDLER_USER PSQL_HANDLER_PASSWORD PSQL_USER PSQL_PASSWORD

  bot-postgres:
    <<: *bot-common
    image: postgres:15
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - ./pgdata:/var/lib/postgresql/data     # uncomment this before deploy
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d tgbot"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 10s
    restart: unless-stopped
