# Environment variables must be declared in .env file
version: '3'

services:
  pginit:
    build: postgres-init
    container_name: postgres-init
    environment:
      DBNAME: ${DBNAME}
      SCHEMA: ${SCHEMA}
      PSQL_HANDLER_USER: ${PSQL_HANDLER_USER}
      PSQL_HANDLER_PASSWORD: ${PSQL_HANDLER_PASSWORD}
      PSQL_USER: ${PSQL_USER}
      PSQL_PASSWORD: ${PSQL_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: sh -c "envsubst < /docker-entrypoint-initdb.d/init.sqltemplate > /docker-entrypoint-initdb.d/init.sql"

  cmcis-postgres:
    image: postgres:15
    container_name: ${DBHOST}
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${PSQL_MASTER_USER}
      POSTGRES_PASSWORD: ${PSQL_MASTER_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432        
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${DBNAME}"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  
  cmcis-bot:
    build: .
    entrypoint: /bin/bash
    command:
      - -c
      - |
        export DBHOST=${DBHOST} DBPORT=${DBPORT} DBNAME=${DBNAME} SCHEMA=${SCHEMA} TGTOKEN=${TGTOKEN} PSQL_USER=${PSQL_USER}
        envsubst < template.cnf > my.cnf
        /home/bot/venv/bin/python3 keystore.py -s telegram -u botuser -p $TGTOKEN
        /home/bot/venv/bin/python3 keystore.py -s $DBNAME -u $PSQL_USER -p $PSQL_PASSWORD
        /home/bot/venv/bin/python3 bot.py
        unset DBHOST DBPORT DBNAME SCHEMA TGTOKEN PSQL_USER
    depends_on:
      - cmcis-postgres
    restart: unless-stopped
